E-Election Voting/Demo.Web/Areas/Admin/Controllers/HomeController.cs
using Autofac;
using Demo.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadResults();
            model.LoadUpcomingElections();
            model.LoadElections();
            model.LoadCandidatesCount();
            model.LoadVotersCount();
            return View(model);
        }
    }
}

E-Election Voting/Demo.Web/Controllers/ElectionController.cs
using Autofac;
using Demo.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Dynamic;
using System.Threading.Tasks;
using Demo.Foundation.Entities;
using System.Security.Claims;

namespace Demo.Web.Controllers
{
    public class ElectionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAllElection()
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadElections();
            return View(model);
        }
        public IActionResult GetAllUpcomingElection() 
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadUpcomingElections();
            return View(model);
        }
        public IActionResult GetSingleUpcomingElection(int id) 
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadSingleMakeElection(id);
            return View(model);
        }
        public IActionResult GetElection(int id)
        {
            var UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadVoterCheck(id, UserId);
            model.LoadSingleMakeElection(id);
            model.LoadSingleVoter(UserId);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GetElection(ViewModel viewData)
        {
            viewData.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = Startup.AutofacContainer.Resolve<AdditionModel>();
            model.AddModelElectionPOST(viewData);
            return RedirectToAction(nameof(GetAllElection));
        }
        public IActionResult GetCandidate(int id)
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadSingleCandidate(id);
            return View(model);
        }
        public IActionResult ViewResults()
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadResults();
            return View(model);
        }
    }
}

E-Election Voting/Demo.Web/Controllers/HomeController.cs
using Demo.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Autofac;

namespace Demo.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadResults();
            model.LoadUpcomingElections();
            model.LoadElections();
            return View(model);
        }
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-Election Voting/Demo.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<b>
    <div class="container">
        <h2><b>About</b></h2>
        <h4>
            E-Election Voting is the easiest way to improve voter engagement, save time, create a better voter experience, and guarantee election integrity.Elections is our first name and democracy is in our DNA. We are committed to your satisfaction
        </h4>
    </div>
</b>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Demo.Membership.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model ViewModel;
@{
    ViewData["Title"] = "Home";
}
<link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
<link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
<link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
<link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
<link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
<link href="~/assets/css/style.css" rel="stylesheet">

<section id="hero" class="d-flex align-items-center">
    <div class="container-fluid" data-aos="zoom-out" data-aos-delay="100">
        <div class="row justify-content-center">
            <div class="col-xl-10">
                <div class="row">
                    <div class="col-xl-5">
                        <h1>Bettter voting experience with</h1>
                        <h1>E-Election Voting</h1>
                        <h2>Cast your vote online</h2>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a asp-controller="Election" asp-action="GetAllElection" class="btn-get-started scrollto">Get Started</a>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login" class="btn-get-started scrollto">Get Started</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="counts" class="counts">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="count-box">
                    <i class="icofont-simple-smile"></i>
                    <span data-toggle="counter-up">@Model.TotalElectionsCount</span>
                    <p>Total Elections</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
                <div class="count-box">
                    <i class="icofont-document-folder"></i>
                    <span data-toggle="counter-up">@Model.RunningElectionCount</span>
                    <p>Running Elections</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
                <div class="count-box">
                    <i class="icofont-live-support"></i>
                    <span data-toggle="counter-up">@Model.UpcomingElectionCount</span>
                    <p>Upcoming Elections</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
                <div class="count-box">
                    <i class="icofont-users-alt-5"></i>
                    <span data-toggle="counter-up">@Model.ConcretedElectionCount</span>
                    <p>Completed </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="faq" class="faq">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Frequently Asked Questions</h2>
        </div>
        <ul class="faq-list" data-aos="fade-up">
            <li>
                <a data-toggle="collapse" class="collapsed" href="#faq1">How do voters access the ballot? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-x icon-close"></i></a>
                <div id="faq1" class="collapse" data-parent=".faq-list">
                    <p>
                        If hosting the election on the ElectionsOnline website as opposed to your own website, each voter will need a username and password in order to access the ballot. If you already have this data for your voters and wish to include it when submitting the voter roster, you may. Otherwise, ElectionsOnline will generate a username and password for each voter that will be good only for a single election
                    </p>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#faq2" class="collapsed">How is a voter prevented from double-voting ? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-x icon-close"></i></a>
                <div id="faq2" class="collapse" data-parent=".faq-list">
                    <p> Insert ballot into the system only when the voter has not previously voted.
                    </p>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#faq3" class="collapsed">Is the system mobile friendly? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-x icon-close"></i></a>
                <div id="faq3" class="collapse" data-parent=".faq-list">
                    <p>
                        Yes. Employing responsive design, the ballot displays well on all devices.
                    </p>
                </div>
            </li>
        </ul>
    </div>
</section>
<section id="team" class="team section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Team</h2>
            <p></p>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-2 d-flex align-items-stretch">
                <div class="member" data-aos="fade-up" data-aos-delay="300">
                    <div class="member-img">
                        <img src="~/images/SuperVisor.png" height="550" width="500" alt="">
                        <div class="social">
                            <a href=""><i class="icofont-twitter"></i></a>
                            <a href=""><i class="icofont-facebook"></i></a>
                            <a href=""><i class="icofont-instagram"></i></a>
                            <a href=""><i class="icofont-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="member-info">
                        <h4>Sk. Fazlee Rabby</h4>
                        <b>Project supervisor</b>
                    </div>  
                </div>
            </div>
            <div class="col-lg-6 col-md-2 d-flex align-items-stretch">
                <div class="member" data-aos="fade-up" data-aos-delay="400">
                    <div class="member-img">
                        <img src="~/images/Rashed.png" height="550" width="500" alt="">
                        <div class="social">
                            <a href=""><i class="icofont-twitter"></i></a>
                            <a href=""><i class="icofont-facebook"></i></a>
                            <a href=""><i class="icofont-instagram"></i></a>
                            <a href=""><i class="icofont-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="member-info">
                        <h4>Rashed Bean Nayem</h4>
                        <b>Developer</b>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="contact" class="contact">
    <b>
        <div class="container" data-aos="fade-up">
            <div class="section-title">
                <h2>Contact</h2>
                <p>Please feel free to contact us with any inquiry</p>
            </div>
            <div class="row" data-aos="fade-up" data-aos-delay="100">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="info-box">
                                <i class="bx bx-map"></i>
                                <h3>Our Address</h3>
                                <p>Savar DOHS, Savar, Dhaka.</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box mt-4">
                                <i class="bx bx-envelope"></i>
                                <h3>Email Us</h3>
                                <p>rashed35-242@diu.edu.bd@*<br>contact@example.com</p>*@
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box mt-4">
                                <i class="bx bx-phone-call"></i>
                                <h3>Call Us</h3>
                                <p>01680935570@*<br>+1 6678 254445 41</p>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <form action="~/forms/contact.php" method="post" role="form" class="php-email-form">
                        <div class="form-row">
                            <div class="col form-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validate"></div>
                            </div>
                            <div class="col form-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            <div class="validate"></div>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                            <div class="validate"></div>
                        </div>
                        <div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center"><button type="submit">Send Message</button></div>
                    </form>
                </div>
            </div>
        </div>
    </b>
</section>

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
<script src="~/assets/vendor/jquery/jquery.min.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="~/assets/vendor/php-email-form/validate.js"></script>
<script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
<script src="~/assets/vendor/counterup/counterup.min.js"></script>
<script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="~/assets/vendor/venobox/venobox.min.js"></script>
<script src="~/assets/vendor/aos/aos.js"></script>
<script src="~/assets/js/main.js"></script>