E-Election Voting/Demo.Web/Areas/Admin/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Microsoft.AspNetCore.Mvc;
using Demo.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Demo.Foundation.BusinessObjects;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Demo.Web.Areas.Admin.Models;

namespace Demo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class CandidateController : Controller 
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CandidateApiForm()
        {         
            return View();
        }
        public IActionResult GetCandidate(int id)
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            model.LoadSingleCandidate(id);
            return View(model);
        }
        [HttpPost]
        [Route("AddCandidate")]
        public IActionResult AddCandidate(IFormCollection collection)  
        {
            string user2 = collection["userNid"];
            var model = Startup.AutofacContainer.Resolve<ApiRecordForCandidateData>();
            model.LoadSingleApiRecord(user2);
            model.LoadSingleCheckApiNid(user2);
            return View(model);
        }
        [ValidateAntiForgeryToken, HttpPost]
        [Route("CandidatePost")]
        public IActionResult CandidatePost(ApiRecordForCandidateData data) 
        {     
            var model = Startup.AutofacContainer.Resolve<AdditionModel>();
            model.AddModelCandidate(data);
            return RedirectToAction(nameof(GetAllCandidateDataTable));
        }
        public IActionResult GetAllCandidateDataTable()
        {
            var model = Startup.AutofacContainer.Resolve<RegistrationData>();
            model.LoadCandidates();
            return View(model);
        }
        public IActionResult CandidateProfileUpdate(int id)
        {
            ViewBag.CanId = id;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CandidateProfileUpdate(ElectionCandidateDataBO electionCandidateDataBO) 
        {
            var model = Startup.AutofacContainer.Resolve<AdditionModel>();
            model.AddModelCandidateUpdate(electionCandidateDataBO);
            return RedirectToAction(nameof(GetCandidate), new { id = electionCandidateDataBO.Id });
        }
        public IActionResult DeleteSingleCandidate(int id) 
        {
            var model = Startup.AutofacContainer.Resolve<DeleteModel>();
            model.DeleteCandidate(id);
            return RedirectToAction(nameof(GetAllCandidateDataTable));
        }
    }
}

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/AddCandidate.cshtml
@{
    ViewData["Title"] = "Add Candidate";
}
@model ApiRecordForCandidateData;

@if (@Model.ApiClasses.ApiName != null && @Model.ElectionVoterCheck.Count == 0 && @Model.ElectionCandidateCheck.Count == 0)
{
    <div class="container">
        <div class="col-md-10">
            <div class="card card-primary">
                <div class="card-header">
                    <h3>Candidate Form</h3>
                </div>
                <form method="post" asp-area="Admin" asp-controller="Candidate" asp-action="CandidatePost" asp-antiforgery="true" enctype="multipart/form-data">
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <label asp-for="FirstName"></label>
                                <input asp-for="FirstName" class="form-control" value="@Model.ApiClasses.ApiName" readonly>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="NID"></label>
                                <input asp-for="NID" class="form-control" value="@Model.ApiClasses.ApiNid" readonly>
                            </div>
                            <div class="col">
                                <label asp-for="DateOfBirth"></label>
                                <input type="datetime" asp-for="DateOfBirth" class="form-control" value="@Model.ApiClasses.ApiDateOfBirth" readonly>
                            </div>
                            <div class="col">
                                <label asp-for="PdfListBOfiles"></label>
                                <input type="file" asp-for="PdfListBOfiles" class="form-control" multiple required="required">
                                <span asp-validation-for="PdfListBOfiles" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Mobile"></label>
                                <input asp-for="Mobile" class="form-control" placeholder="Mobile" required="required">
                                <span asp-validation-for="Mobile" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="ImageFile"></label>
                                <input type="file" asp-for="ImageFile" class="form-control" required="required">
                                <span asp-validation-for="ImageFile" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Address"></label>
                                <input asp-for="Address" class="form-control" placeholder="Address" required="required">
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" placeholder="About" required="required">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Motto"></label>
                                <input asp-for="Motto" class="form-control" placeholder="Motto" required="required">
                                <span asp-validation-for="Motto" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="LogoImageFile"></label>
                                <input type="file" asp-for="LogoImageFile" class="form-control" required="required">
                                <span asp-validation-for="LogoImageFile" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Add Candidate" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <br />
        <br />
        <font color="red"><h3><b>Please enter your valid NID number for registration.</b></h3></font>
    </div>
}

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/Candidate.cshtml
@*@{
    ViewData["Title"] = "Add Candidate";
}
@model ApiRecordForCandidateData;

@if (@Model.ApiClasses.ApiName != null && @Model.ElectionVoterCheck.NID == null)
{

    <div class="container">
        <div class="col-md-10">
            <div class="card card-primary">
                <div class="card-header">
                    <h3>Candidate Form</h3>
                </div>
                <form method="post" asp-area="Admin" asp-controller="Candidate" asp-action="CandidatePost" asp-antiforgery="true" enctype="multipart/form-data">
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <label asp-for="FirstName"></label>
                                <input asp-for="FirstName" class="form-control" value="@Model.ApiClasses.ApiName" readonly">
                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="NID"></label>
                                <input asp-for="NID" class="form-control" value="@Model.ApiClasses.ApiNid">
                               
                            </div>
                            <div class="col">
                                <label asp-for="DateOfBirth"></label>
                                <input asp-for="DateOfBirth" class="form-control" value="@Model.ApiClasses.ApiDateOfBirth" readonly>
                              
                            </div>
                            <div class="col">
                                <label asp-for="PdfListBOfiles"></label>
                                <input type="file" asp-for="PdfListBOfiles" class="form-control" multiple>
                                <span asp-validation-for="PdfListBOfiles" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Mobile"></label>
                                <input asp-for="Mobile" class="form-control" placeholder="Mobile">
                                <span asp-validation-for="Mobile" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="ImageFile"></label>
                                <input type="file" asp-for="ImageFile" class="form-control">
                                <span asp-validation-for="ImageFile" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Address"></label>
                                <input asp-for="Address" class="form-control" placeholder="Address">
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" placeholder="About">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label asp-for="Motto"></label>
                                <input asp-for="Motto" class="form-control" placeholder="Motto">
                                <span asp-validation-for="Motto" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <label asp-for="LogoImageFile"></label>
                                <input type="file" asp-for="LogoImageFile" class="form-control">
                                <span asp-validation-for="LogoImageFile" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Add Candidate" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

}
else
{
    <div class="container">
        <br />
        <br />
        <font color="red"><h3><b>Please enter your valid NID number for registration.</b></h3></font>
    </div>
}*@

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/CandidateApiForm.cshtml
@{
    ViewData["Title"] = "NID Verification";
}

    <div class="container">    
                <br />
                <br />
                <font color="black">
                    <h5> <b> Provide the National Identity Card number in the form below and click on the "Verify" button.Then, can see candidate registration further status.</b> </h5>
                </font>
                <form method="post" asp-area="admin" asp-controller="Candidate" asp-action="AddCandidate" asp-antiforgery="true" enctype="multipart/form-data">
                    <font color="black"><b>National Identity Card Number:</b></font>
                    <div class="form-group">
                        <input type="number" name="userNid" id="korisnik" pattern="/^-?\d+\.?\d*$/" onKeyPress="if(this.value.length==10)  return false;" required="required" placeholder="Example-1234567890" class="form-control" />
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" title="Login" value="Verify" class="btn btn-primary form-control" />
                    </div>
                </form>
    </div>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/CandidateProfileUpdate.cshtml
@{
    ViewData["Title"] = "Update Candidate Profile";
}

@model ElectionCandidateDataBO;

<style>

    /*body {
        background: -webkit-linear-gradient(left, #3931af, #00c6ff);
    }*/

    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 30%;
            height: 40%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 70%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>

<div class="container rounded bg-white mt-4 mb-5">
    <div class="row">
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <h3>Edit Candidate Profile</h3>
                <form method="post" asp-area="admin" asp-controller="Candidate" asp-action="CandidateProfileUpdate" asp-antiforgery="true" enctype="multipart/form-data">              
                        <input asp-for="Id" class="form-control" value="@ViewBag.CanId" hidden>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label asp-for="Mobile"></label>
                            <input asp-for="Mobile" class="form-control" placeholder="Mobile" required="required">
                            <span asp-validation-for="Mobile" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Description"></label>
                            <input asp-for="Description" class="form-control" placeholder="About" required="required">
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Motto"></label>
                            <input asp-for="Motto" class="form-control" placeholder="Motto" required="required">
                            <span asp-validation-for="Motto" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label asp-for="Address"></label>
                            <input asp-for="Address" class="form-control" placeholder="Address" required="required">
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="ImageFile"></label>
                            <input type="file" asp-for="ImageFile" class="form-control" required="required">
                            <span asp-validation-for="ImageFile" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="LogoImageFile"></label>
                            <input type="file" asp-for="LogoImageFile" class="form-control" required="required">
                            <span asp-validation-for="LogoImageFile" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <button class="btn btn-primary profile-button" type="submit">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <input type="button" onclick="history.go(-1)" value="Back" />
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/GetAllCandidateDataTable.cshtml
@{
    ViewData["Title"] = "All Candidates";
}
@model RegistrationData;
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">

<div class="container">
    <h3><b>Candidates</b></h3>
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th><h5><b>Candidate Photo</b></h5></th>
                <th><h5><b>Candidate Name</b></h5></th>
                <th><h5><b>Candidate Address</b></h5></th>
                <th><h5><b>Action</b></h5></th>
                <th><h5><b>Action</b></h5></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var candidate in Model.ElectionCandidates)
            {
            <tr>
                <td><b></b><img src="@candidate.ImageUrl" alt="Profile Photo" width="40" height="40" /></td>
                <td><b>@candidate.Name</b></td>
                <td><b>@candidate.Address</b></td>
                <td><b><a asp-area="admin" asp-controller="Candidate" asp-action="GetCandidate" asp-route-id=@candidate.Id class="btn btn-sm btn-primary">Details</a></b></td>
                <td><b><a asp-area="admin" asp-controller="Candidate" asp-action="DeleteSingleCandidate" asp-route-id=@candidate.Id class="btn btn-sm btn-danger">Delete</a></b></td>
            </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

E-Election Voting/Demo.Web/Areas/Admin/Views/Candidate/GetCandidate.cshtml
@{
    ViewData["Title"] = "Candidate Details";
}
@{
    dynamic data = ViewBag.Data;
}
@model ViewModel;

<style>
    /* body {
        background: -webkit-linear-gradient(left, #3931af, #00c6ff);
    }*/

    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 30%;
            height: 10%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 70%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="@Model.ElectionCandidate.ImageUrl" width="100" height="50" alt="" />

                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        @Model.ElectionCandidate.Name
                    </h5>
                    <h6>
                        Registered Candidate
                    </h6>

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                            </li>*@
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <a asp-area="admin" asp-controller="Candidate" asp-action="CandidateProfileUpdate" asp-route-id=@Model.ElectionCandidate.Id  name="btnAddMore"><button class="btn btn-primary" type="button">Edit Profile</button></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p><b>Documents</b></p>
                    <div class="col-md-8">
                        @foreach (var item in Model.ElectionCandidate.PdfListUrl)
                        {
                            <a class="btn btn-outline-primary" href="@item.URL" target="_blank">@item.Name</a>
                            <p></p>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>NID</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.NID</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Date Of Birtg</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.DateOfBirth</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Address</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.Address</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.Mobile</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>About</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.Description</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Motto</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionCandidate.Motto</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Logo</label>
                            </div>
                            <div class="col-md-6">
                                <img src="@Model.ElectionCandidate.LogoImageUrl" width="100" height="50" alt="Profile Photo" />
                            </div>
                            
                        </div> 
                        <div class="row">
                            <div class="col-md-6">
                                
                            </div>
                            <div class="col-md-6">
                                <p></p>
                                <input type="button" onclick="history.go(-1)" value="Back" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>