E-Election Voting/Demo.Web/Areas/Admin/Controllers/VoterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Demo.Foundation.Entities;
using Microsoft.AspNetCore.Mvc;
using Demo.Web.Areas.Admin.Data;
using Microsoft.AspNetCore.Authorization;
using Demo.Foundation.BusinessObjects;
using System.Security.Claims;
using System.Linq;

namespace Demo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class VoterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Voter()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Voter(ElectionVoterDataBO electionVoterData) 
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                var model = Startup.AutofacContainer.Resolve<IndexModel>();
                model.AddModelVoter(electionVoterData);
                return RedirectToAction(nameof(Voter));               
            }
            return View();

        }

    }
}

E-Election Voting/Demo.Web/Controllers/VoterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Demo.Foundation.Entities;
using Microsoft.AspNetCore.Mvc;
using Demo.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Demo.Foundation.BusinessObjects;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;

namespace Demo.Web.Controllers
{
    public class VoterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult VoterSms() 
        {
            return View();
        }
        public IActionResult VoterApiForm()
        {          
            return View();
        }
       
        [HttpPost]
        [Route("AddVoter")]
        public IActionResult AddVoter(IFormCollection collection)
        {
            string user2 = collection["userNid"];
            var model = Startup.AutofacContainer.Resolve<ApiRecordFormData>();
            model.LoadSingleApiRecord(user2);
            model.LoadSingleCheckApiNid(user2);          
            return View(model);
        }
        public IActionResult AddVoterUpdate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddVoterUpdate(ApiRecordFormData apiRecordFormData)
        {
            apiRecordFormData.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = Startup.AutofacContainer.Resolve<AdditionModel>();
            model.AddModelVoterUpdate(apiRecordFormData);
            return RedirectToAction(nameof(VoterProfile));
        }   
        public ViewResult VoterProfile()
        {
            var model = Startup.AutofacContainer.Resolve<ViewModel>();
            var UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            model.LoadSingleVoter(UserId);
            return View(model);
        }
    }
}

E-Election Voting/Demo.Web/Views/Voter/AddVoter.cshtml
@{
    ViewData["Title"] = "Registration";
}
@model ApiRecordFormData;

<style>
    /*body {
        font-family: 'Roboto', sans-serif;
    }*/

    .form-control {
        height: 30px;
        box-shadow: none;
        color: #969fa4;
    }

    .error {
        color: red;
    }

    .form-control:focus {
        border-color: #5cb85c;
    }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 450px;
        margin: 0 auto;
        padding: 20px 0;
        font-size: 15px;
    }

        .signup-form h5 {
            color: #636363;
            margin: 0 0 15px;
            position: relative;
            text-align: center;
        }

            .signup-form h5:before, .signup-form h5:after {
                content: "";
                height: 2px;
                width: 30%;
                background: #d4d4d4;
                position: absolute;
                top: 50%;
                z-index: 2;
            }

            .signup-form h5:before {
                left: 0;
            }

            .signup-form h5:after {
                right: 0;
            }

        .signup-form .hint-text {
            color: #999;
            margin-bottom: 30px;
            text-align: center;
        }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #f2f3f7;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 25px;
        }

        .signup-form .form-group {
            margin-bottom: 0px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 5px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            min-width: 140px;
            outline: none !important;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #5cb85c;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }
</style>
@if (@Model.ApiClasses.ApiName != null && @Model.ElectionVoterCheck.Count == 0 && @Model.ElectionCandidateCheck.Count == 0)
{
    <body>
        <b>
            <div class="signup-form">
                <form method="post" asp-route-returnUrl="@Model.ReturnUrl" asp-area="" asp-controller="Account" asp-action="Register" asp-antiforgery="true" enctype="multipart/form-data">
                    <h5>Sign Up</h5>
                    <div class="form-group">
                        <b><label asp-for="FirstName"></label></b>
                        <input asp-for="FirstName" class="form-control" value="@Model.ApiClasses.ApiName" readonly>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <b><label asp-for="DateOfBirth"></label></b>
                                <input type="datetime" asp-for="DateOfBirth" class="form-control" value="@Model.ApiClasses.ApiDateOfBirth" readonly>
                            </div>
                            <div class="col-md-6">
                                <b><label asp-for="NID"></label></b>
                                <input asp-for="NID" class="form-control" value="@Model.ApiClasses.ApiNid" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <b><label asp-for="Email"></label></b>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <b><label asp-for="Password"></label></b>
                                <input asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <b><label asp-for="ConfirmPassword"></label></b>
                                <input asp-for="ConfirmPassword" class="form-control" />
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    @*<div class="form-group">
                    <label class="form-check-label"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></label>
                </div>*@
                    <br />
                    <div class="form-group">
                        <button type="submit" value="Send" class="btn btn-success btn-lg btn-block">Register Now</button>
                    </div>
                    <div class="text-center">Already have an account? <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Sign in</a></div>
                </form>
            </div>
        </b>
    </body>
}
else
{
<div class="container">
    <br />
    <br />
    <font color="red"><h3><b>Please enter your valid NID number for registration.</b></h3></font>
</div>
    
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Views/Voter/AddVoterUpdate.cshtml
@{
    ViewData["Title"] = "Update Profile";
}

@model ApiRecordFormData;

<style>

    /*body {
        background: -webkit-linear-gradient(left, #3931af, #00c6ff);
    }*/

    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 30%;
            height: 40%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 70%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>

<div class="container rounded bg-white mt-4 mb-5">
    <div class="row">
        <div class="col-md-5 border-right">

            <div class="p-3 py-5">
                <h3>Edit Profile</h3>
                <form method="post" asp-area="" asp-controller="Voter" asp-action="AddVoterUpdate" asp-antiforgery="true" enctype="multipart/form-data">

                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label asp-for="Mobile"></label>
                            <input asp-for="Mobile" class="form-control" placeholder="Mobile" required="required">
                            <span asp-validation-for="Mobile" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label asp-for="Address"></label>
                            <input asp-for="Address" class="form-control" placeholder="Address" required="required">
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CoverPhoto"></label>
                            <input type="file" asp-for="CoverPhoto" class="form-control" required="required">
                            <span asp-validation-for="CoverPhoto" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <button class="btn btn-primary profile-button" type="submit">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
               <input type="button" onclick="history.go(-1)" value="Back" />
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Views/Voter/VoterApiForm.cshtml
@{
    ViewData["Title"] = "NID Verification";
}

<style>
    body {
        font-family: 'Roboto', sans-serif;
    }

    .form-control {
        height: 30px;
        box-shadow: none;
        color: #969fa4;
    }

    .error {
        color: red;
    }

    .form-control:focus {
        border-color: #5cb85c;
    }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 450px;
        margin: 0 auto;
        padding: 20px 0;
        font-size: 15px;
    }

        .signup-form h5 {
            color: #636363;
            margin: 0 0 15px;
            position: relative;
            text-align: center;
        }

            .signup-form h5:before, .signup-form h5:after {
                content: "";
                height: 2px;
                width: 30%;
                background: #d4d4d4;
                position: absolute;
                top: 50%;
                z-index: 2;
            }

            .signup-form h5:before {
                left: 0;
            }

            .signup-form h5:after {
                right: 0;
            }

        .signup-form .hint-text {
            color: #999;
            margin-bottom: 30px;
            text-align: center;
        }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #f2f3f7;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 25px;
        }

        .signup-form .form-group {
            margin-bottom: 0px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 5px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            min-width: 140px;
            outline: none !important;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #5cb85c;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }
</style>
<body>
    <div class="container">
        <br />
        <br />
        <font color="black">
            <h4> <b> Provide your National Identity Card number in the form below and click on the "Verify" button.Then, you can see voting registration further status.</b> </h4>
        </font>    </div>
        <div class="signup-form">
            <form method="post" asp-area="" asp-controller="Voter" asp-action="AddVoter" asp-antiforgery="true" enctype="multipart/form-data">
                <font color="black"><b>National Identity Card Number:</b></font>
                <div class="form-group">
                    <input type="number" name="userNid" id="korisnik" pattern="/^-?\d+\.?\d*$/" onKeyPress="if(this.value.length==10)  return false;" required="required" placeholder="Example-1234567890" class="form-control" />
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" title="Login" value="Verify" class="btn btn-success form-control"/>
                </div>
                <div class="text-center"><b>Already have an account?</b> <a class="nav-link text-dark" asp-controller="Account" asp-action="Login"><b>Sign in</b></a></div>
            </form>
    </div>
</body>


<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Views/Voter/VoterProfile.cshtml
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "User Profile";
}
@model ViewModel;

<style>
    /* body {
            background: -webkit-linear-gradient(left, #3931af, #00c6ff);
        }*/
    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 30%;
            height: 40%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 70%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="@Model.ElectionVoter.CoverPhotoUrl" alt="Profile Photo" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        </br>
                        @Model.ElectionVoter.Name
                    </h5>
                    <h6>
                        Registered Voter
                    </h6>
                </div>
            </div>
            @if (Model.ElectionVoter.NID == null)
            {
                <div class="btn-group col-md-2">
                    <a asp-controller="Voter" asp-action="VoterApiForm" name="btnAddMore"><button class="btn btn-primary profile-button" type="button">Edit Profile</button></a>
                </div>
            }
            else
            {
                <div class="btn-group col-md-2">
                    <a asp-controller="Voter" asp-action="AddVoterUpdate" name="btnAddMore"><button class="btn btn-primary profile-button" type="button">Edit Profile</button></a>
                </div>
            }

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-4">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionVoter.Name</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>@User.Identity.Name</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>NID</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionVoter.NID</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionVoter.Mobile</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Date of Birth</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionVoter.DateOfBirth</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Address</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.ElectionVoter.Address</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

E-Election Voting/Demo.Web/Views/Voter/VoterSms.cshtml
@{
    ViewData["Title"] = "VoterSms";
}
<div class="container">

    <h1>To vote you need to update your profile</h1>
    <div class="btn-group col-md-2">
        <a asp-controller="Voter" asp-action="VoterApiForm" name="btnAddMore"><button class="btn btn-primary profile-button" type="button">Edit Profile</button></a>
    </div>
</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>